# Generated by Django 4.2.30 on 2026-05-22 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('category_type', models.CharField(choices=[('room', 'Room / Rental'), ('hotel', 'Hotel'), ('salon', 'Salon / Beauty'), ('bus', 'Bus / Transport'), ('restaurant', 'Restaurant / Food'), ('other', 'Other')], default='other', max_length=20)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category_icons/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_label', models.CharField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending Review')], default='active', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='listings.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listing_images/')),
                ('url', models.URLField(blank=True, max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalonDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salon_type', models.CharField(choices=[('unisex', 'Unisex Salon'), ('male', 'Male Only'), ('female', 'Female Only'), ('spa', 'Spa & Wellness'), ('nail', 'Nail Studio'), ('bridal', 'Bridal Makeup')], default='unisex', max_length=20)),
                ('services_offered', models.JSONField(blank=True, default=list)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('open_days', models.JSONField(blank=True, default=list)),
                ('home_service_available', models.BooleanField(default=False)),
                ('appointment_required', models.BooleanField(default=False)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salon_detail', to='listings.listing')),
            ],
        ),
        migrations.CreateModel(
            name='RoomDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('flat', 'Flat / Apartment'), ('shared', 'Shared Room'), ('studio', 'Studio'), ('house', 'Full House')], default='single', max_length=20)),
                ('bedrooms', models.PositiveIntegerField(default=1)),
                ('bathrooms', models.PositiveIntegerField(default=1)),
                ('floor_area_sqft', models.PositiveIntegerField(blank=True, null=True)),
                ('is_furnished', models.BooleanField(default=False)),
                ('parking_available', models.BooleanField(default=False)),
                ('wifi_available', models.BooleanField(default=False)),
                ('water_included', models.BooleanField(default=False)),
                ('electricity_included', models.BooleanField(default=False)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('min_stay_months', models.PositiveIntegerField(default=1)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_detail', to='listings.listing')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine_type', models.CharField(choices=[('nepali', 'Nepali'), ('chinese', 'Chinese'), ('indian', 'Indian'), ('continental', 'Continental'), ('italian', 'Italian'), ('fast_food', 'Fast Food'), ('cafe', 'Café'), ('bakery', 'Bakery'), ('mixed', 'Mixed / Multi-cuisine')], default='mixed', max_length=30)),
                ('seating_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('open_days', models.JSONField(blank=True, default=list)),
                ('home_delivery', models.BooleanField(default=False)),
                ('takeaway', models.BooleanField(default=True)),
                ('outdoor_seating', models.BooleanField(default=False)),
                ('vegetarian_options', models.BooleanField(default=True)),
                ('vegan_options', models.BooleanField(default=False)),
                ('menu_images', models.JSONField(blank=True, default=list)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_detail', to='listings.listing')),
            ],
        ),
        migrations.CreateModel(
            name='HotelDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_rating', models.PositiveSmallIntegerField(default=3)),
                ('total_rooms', models.PositiveIntegerField(blank=True, null=True)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('has_restaurant', models.BooleanField(default=False)),
                ('has_pool', models.BooleanField(default=False)),
                ('has_gym', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=True)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_airport_shuttle', models.BooleanField(default=False)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('website', models.URLField(blank=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_detail', to='listings.listing')),
            ],
        ),
        migrations.CreateModel(
            name='BusDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_type', models.CharField(choices=[('tourist', 'Tourist Bus'), ('local', 'Local Bus'), ('express', 'Express Bus'), ('microbus', 'Microbus'), ('private', 'Private Hire'), ('night', 'Night Bus')], default='local', max_length=20)),
                ('origin', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('duration_hours', models.FloatField(blank=True, null=True)),
                ('total_seats', models.PositiveIntegerField(blank=True, null=True)),
                ('ac_available', models.BooleanField(default=False)),
                ('wifi_available', models.BooleanField(default=False)),
                ('operates_daily', models.BooleanField(default=True)),
                ('operate_days', models.JSONField(blank=True, default=list)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bus_detail', to='listings.listing')),
            ],
        ),
        migrations.CreateModel(
            name='SavedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'listing')},
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'category'], name='listings_li_status_5468e2_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'is_featured'], name='listings_li_status_d7bd55_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['city'], name='listings_li_city_e45c53_idx'),
        ),
    ]
